alert_type : mail
#alert_type : zabbix_api

monitoring_system : zabbix
#monitoring_system : hinemos
#monitoring_system : custom

interval_sec_before_now_for_checking : 120

thread:
  num : 4
  timeout_sec_for_waiting_save : 60

log:
  mode: stdout
#  mode: file
  filepath: '/home/batchuser/im_log/im.log'

hosts:
  mail:
    address : 
    port : 110
    user : 
    password : 

  zabbix:
    url : "http://"
    user : 
    password : 

  redmine:
    url : "http://"
    user : 
    password : 

mail:
  subject_header : "INCIDENT:"
  separator_character : ":="

redmine_mapping:
  im_project_id: incident-manager
  cf_id:
    im_alert_id : "93"
    im_recovered_alert_id : "94"
  zabbix:
    tracker_id: "1"
    null_value : "*UNKNOWN*"
    cf_id:
      date : "17"
      esc_history : "18"
      event_ack_history : "19"
      event_ack_status : "20"
      event_age : "21"
      event_date : "22"
      event_id : "75"
      running_event_id : "76"
      event_time : "25"
      hostname : "26"
      host_conn : "27"
      host_dns : "28"
      ipaddress : "29"
      item_lastvalue : "30"
      item_log_age : "31"
      item_log_date : "32"
      item_log_eventid : "79"
      item_log_nseverity : "34"
      item_log_severity : "35"
      item_log_source : "36"
      item_log_time : "37"
      item_name : "38"
      item_value : "39"
      node_id : "77"
      node_name : "41"
      profile_contact : "42"
      profile_devicetype : "43"
      profile_hardware : "44"
      profile_location : "45"
      profile_macaddress : "46"
      profile_name : "47"
      profile_notes : "48"
      profile_os : "49"
      profile_serialno : "50"
      profile_software : "51"
      profile_tag : "52"
      status : "85"
      time : "54"
      trigger_comment : "55"
      trigger_events_unack : "56"
      trigger_id : "78"
      trigger_key : "61"
      trigger_name : "62"
      trigger_nseverity : "81"
      trigger_severity : "86"
      trigger_status : "83"
      trigger_url : "66"
      trigger_value : "82"
      host_key_func_param : "68"
      im_order : "107"
    cf_value:
      trigger_nseverity:
        "0" : 未分類
        "1" : 情報
        "2" : 警告
        "3" : 軽度の障害
        "4" : 重度の障害
        "5" : 致命的な障害
      trigger_severity:
        "Not classified" : 未分類
        "Information"    : 情報
        "Warning"        : 警告
        "Average"        : 軽度の障害
        "High"           : 重度の障害
        "Disaster"       : 致命的な障害
      trigger_status:
        "ON"  : "PROBLEM"
        "OFF" : "OK"
      status:
        "ON"  : "PROBLEM"
        "OFF" : "OK"
      trigger_value:
        "0" : 正常
        "1" : 障害
        "2" : 不明
    cf_translated:
      date : 発生日付
      esc_history : エスカレーションヒストリ
      event_ack_history : イベントACKヒストリ
      event_ack_status : イベントACKステータス
      event_age : イベント時期
      event_date : イベント日付
      event_id : イベントID
      event_time : イベント時刻
      hostname : ホスト名
      host_conn : IPとホストDNS名
      host_dns : ホストDNS名
      ipaddress : IPアドレス
      item_lastvalue : アイテムの最新値
      item_log_age : アイテムログ時期
      item_log_date : アイテムログ日付
      item_log_eventid : アイテムログイベントID
      item_log_nseverity : アイテムログ深刻度（数値）
      item_log_severity : アイテムログ深刻度
      item_log_source : アイテムログソース
      item_log_time : アイテムログ時刻
      item_name : アイテム名
      item_value : アイテムの値
      node_id : ノードID
      node_name : ノード名
      profile_contact : 連絡先
      profile_devicetype : デバイス名
      profile_hardware : ハードウェア
      profile_location : 場所
      profile_macaddress : MACアドレス
      profile_name : （プロファイル上の）名前
      profile_notes : （プロファイル上の）備考
      profile_os : OS
      profile_serialno : シリアルNo
      profile_software : ソフトウェア
      profile_tag : タグ
      status : ステータス
      time : 現在時刻
      trigger_comment : トリガーコメント
      trigger_events_unack : 未応答イベント数
      trigger_events_problem_unack: 状態無視未応答障害イベント数
      trigger_problem_events_problem_unack: 障害トリガー未応答障害イベント数
      trigger_id : トリガーID
      trigger_key : トリガーアイテムキー
      trigger_name : トリガー名
      trigger_nseverity : トリガー深刻度（数値）
      trigger_severity : トリガー深刻度
      trigger_status : トリガーステータス
      trigger_url : トリガーURL
      trigger_value : トリガーの値
  hinemos:
    tracker_id: "4"
    cf_id:
      priority : "97"
      priority_jp : "97"
      priority_en : "97"
      priority_num : "97"
      generation_date : "103"
      plugin_id : "87"
      monitor_id : "99"
      facility_id : "100"
      scope : "88"
      aplication : "89"
      message_id : "106"
      message : "104"
      org_message : "105"
      ip_address : "101"
      node : "102"
    cf_value:
      priority_num:
        "0" : 危険
        "1" : 不明
        "2" : 警告
        "3" : 情報
      priority_to_trigger_value:
        "0" : 障害
        "1" : 不明
        "2" : 障害
        "3" : 正常
    cf_translated:
      priority : 重要度
      priority_jp : 重要度（日本語）
      priority_en : 重要度（英語）
      priority_num : 重要度（数値）
      generation_date : 出力日時
      plugin_id : プラグインID
      monitor_id : モニター
      facility_id : ファシリティID
      scope : スコープ
      aplication : アプリケーション
      message_id : メッセージID
      message : メッセージ
      org_message : オリジナルメッセージ
      ip_address : IPアドレス
      node : ノード名
  custom:
    tracker_id:
    cf_id:
    cf_value:
    cf_tramslated:
