alert_type : mail
#alert_type : zabbix_api

monitoring_system : zabbix
#monitoring_system : hinemos
#monitoring_system : custom

interval_sec_before_now_for_checking : 300

thread:
  num : 4
  timeout_sec_for_waiting_save : 60

mail:
  subject_header : "INCIDENT:"
  separator_character : ":="

log:
  #mode: stdout
  mode: file
  filepath: "/var/lib/redmine/log/"
  rotate_max_bytes: 10485760
  rotate_backup_count: 5

hosts:
  redmine:
    url : "http://localhost/redmine/"
    user : admin
    password : admin
    api_key : ""

    database:
      host : localhost
      db_name : ""
      user : ""
      password : ""

  mail:
    address : ""
    port : 110
    user : 
    password : 

  zabbix:
    url : "http://"
    user : 
    password : 

flg:
  ## チケット作成時にプロジェクトメンバー全員をウォッチャーに追加するかを判定するフラグ（true or false）
  auto_add_watchers : false

redmine_mapping:
  im_project_id: incident-manager
  ## alert_typeがzabbix_apiの際に、件名が空のアラートを登録する際に利用される（起票不要の場合は設定不要）
  default_subject:
  cf_id:
    im_alert_id : "51"
    im_recovered_alert_id : "52"
  zabbix:
    tracker_id: "1"
    null_value : "*UNKNOWN*"
    cf_id:
      im_order : "62"
      date : "1"
      esc_history : "2"
      event_ack_history : "3"
      event_ack_status : "4"
      event_age : "5"
      event_date : "6"
      event_id : "39"
      event_time : "7"
      hostname : "8"
      host_conn : "9"
      host_dns : "10"
      ipaddress : "11"
      item_lastvalue : "12"
      item_log_age : "13"
      item_log_date : "14"
      item_log_eventid : "42"
      item_log_nseverity : "15"
      item_log_severity : "16"
      item_log_source : "17"
      item_log_time : "18"
      item_name : "19"
      item_value : "20"
      node_id : "40"
      node_name : "21"
      profile_contact : "22"
      profile_devicetype : "23"
      profile_hardware : "24"
      profile_location : "25"
      profile_macaddress : "26"
      profile_name : "27"
      profile_notes : "28"
      profile_os : "29"
      profile_serialno : "30"
      profile_software : "31"
      profile_tag : "32"
      status : "46"
      time : "33"
      trigger_comment : "34"
      trigger_events_unack : "35"
      trigger_id : "41"
      trigger_key : "36"
      trigger_name : "37"
      trigger_nseverity : "43"
      trigger_severity : "47"
      trigger_status : "45"
      trigger_url : "38"
      trigger_value : "44"
    cf_value:
      trigger_nseverity:
        "0" : 未分類
        "1" : 情報
        "2" : 警告
        "3" : 軽度の障害
        "4" : 重度の障害
        "5" : 致命的な障害
      trigger_severity:
        "Not classified" : 未分類
        "Information"    : 情報
        "Warning"        : 警告
        "Average"        : 軽度の障害
        "High"           : 重度の障害
        "Disaster"       : 致命的な障害
      trigger_status:
        "ON"  : "PROBLEM"
        "OFF" : "OK"
      status:
        "ON"  : "PROBLEM"
        "OFF" : "OK"
      trigger_value:
        "0" : 正常
        "1" : 障害
        "2" : 不明
    cf_translated:
      date : 発生日付
      esc_history : エスカレーションヒストリ
      event_ack_history : イベントACKヒストリ
      event_ack_status : イベントACKステータス
      event_age : イベント時期
      event_date : イベント日付
      event_id : イベントID
      event_time : イベント時刻
      hostname : ホスト名
      host_conn : IPとホストDNS名
      host_dns : ホストDNS名
      ipaddress : IPアドレス
      item_lastvalue : アイテムの最新値
      item_log_age : アイテムログ時期
      item_log_date : アイテムログ日付
      item_log_eventid : アイテムログイベントID
      item_log_nseverity : アイテムログ深刻度（数値）
      item_log_severity : アイテムログ深刻度
      item_log_source : アイテムログソース
      item_log_time : アイテムログ時刻
      item_name : アイテム名
      item_value : アイテムの値
      node_id : ノードID
      node_name : ノード名
      profile_contact : 連絡先
      profile_devicetype : デバイス名
      profile_hardware : ハードウェア
      profile_location : 場所
      profile_macaddress : MACアドレス
      profile_name : （プロファイル上の）名前
      profile_notes : （プロファイル上の）備考
      profile_os : OS
      profile_serialno : シリアルNo
      profile_software : ソフトウェア
      profile_tag : タグ
      status : ステータス
      time : 現在時刻
      trigger_comment : トリガーコメント
      trigger_events_unack : 未応答イベント数
      trigger_events_problem_unack: 状態無視未応答障害イベント数
      trigger_id : トリガーID
      trigger_key : トリガーアイテムキー
      trigger_name : トリガー名
      trigger_nseverity : トリガー深刻度（数値）
      trigger_severity : トリガー深刻度
      trigger_status : トリガーステータス
      trigger_url : トリガーURL
      trigger_value : トリガーの値
  hinemos:
    tracker_id: "4"
    null_value : ""
    cf_id:
      priority : "53"
      priority_jp : "53"
      priority_en : "53"
      priority_num : "53"
      generation_date : "58"
      plugin_id : "48"
      monitor_id : "54"
      facility_id : "55"
      scope : "49"
      aplication : "50"
      message_id : "61"
      message : "59"
      org_message : "60"
      ip_address : "56"
      node : "57"
    cf_value:
      priority_num:
        "0" : 危険
        "1" : 不明
        "2" : 警告
        "3" : 情報
    cf_translated:
      priority : 重要度
      priority_jp : 重要度（日本語）
      priority_en : 重要度（英語）
      priority_num : 重要度（数値）
      generation_date : 出力日時
      plugin_id : プラグインID
      monitor_id : モニター
      facility_id : ファシリティID
      scope : スコープID
      aplication : アプリケーション
      message_id : メッセージID
      message : メッセージ
      org_message : オリジナルメッセージ
      ip_address : IPアドレス
      node : ノード名
  custom :
    tracker_id :
    null_value : ""
    cf_id :
    cf_value :
    cf_translated :

